# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'current-exporting-projects.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 650)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../xdg/openshot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(10, 10, 360, 630))
        self.listView.setObjectName("listView")
        self.btnAdd = QtWidgets.QPushButton(Dialog)
        self.btnAdd.setGeometry(QtCore.QRect(380, 20, 160, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnAdd.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Compass/actions/misc/contact-new.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon1)
        self.btnAdd.setIconSize(QtCore.QSize(48, 48))
        self.btnAdd.setObjectName("btnAdd")
        self.btnModified = QtWidgets.QPushButton(Dialog)
        self.btnModified.setGeometry(QtCore.QRect(380, 110, 160, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnModified.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/Compass/actions/edit-toolbar/document-export.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModified.setIcon(icon2)
        self.btnModified.setIconSize(QtCore.QSize(48, 48))
        self.btnModified.setObjectName("btnModified")
        self.btnRename = QtWidgets.QPushButton(Dialog)
        self.btnRename.setGeometry(QtCore.QRect(380, 200, 160, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnRename.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/Compass/actions/edit-toolbar/document-page-setup.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRename.setIcon(icon3)
        self.btnRename.setIconSize(QtCore.QSize(48, 48))
        self.btnRename.setObjectName("btnRename")
        self.btnCopy = QtWidgets.QPushButton(Dialog)
        self.btnCopy.setGeometry(QtCore.QRect(380, 290, 160, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnCopy.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/Compass/actions/edit-toolbar/edit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCopy.setIcon(icon4)
        self.btnCopy.setIconSize(QtCore.QSize(48, 48))
        self.btnCopy.setObjectName("btnCopy")
        self.btnDelete = QtWidgets.QPushButton(Dialog)
        self.btnDelete.setGeometry(QtCore.QRect(380, 380, 160, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnDelete.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/Compass/actions/misc/edit-delete.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon5)
        self.btnDelete.setIconSize(QtCore.QSize(48, 48))
        self.btnDelete.setObjectName("btnDelete")
        self.btnClose = QtWidgets.QPushButton(Dialog)
        self.btnClose.setGeometry(QtCore.QRect(380, 560, 160, 70))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnClose.setFont(font)
        self.btnClose.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/Compass/actions/misc/button-cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnClose.setIcon(icon6)
        self.btnClose.setIconSize(QtCore.QSize(48, 48))
        self.btnClose.setObjectName("btnClose")
        self.btnnamelistpreset = QtWidgets.QPushButton(Dialog)
        self.btnnamelistpreset.setGeometry(QtCore.QRect(10, 10, 360, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.btnnamelistpreset.setFont(font)
        self.btnnamelistpreset.setObjectName("btnnamelistpreset")

        self.retranslateUi(Dialog)
        self.btnClose.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.btnAdd, self.btnModified)
        Dialog.setTabOrder(self.btnModified, self.btnRename)
        Dialog.setTabOrder(self.btnRename, self.btnCopy)
        Dialog.setTabOrder(self.btnCopy, self.btnDelete)
        Dialog.setTabOrder(self.btnDelete, self.btnnamelistpreset)
        Dialog.setTabOrder(self.btnnamelistpreset, self.btnClose)
        Dialog.setTabOrder(self.btnClose, self.listView)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Current Exporting Projects"))
        self.btnAdd.setText(_translate("Dialog", "Add"))
        self.btnModified.setText(_translate("Dialog", "Modified"))
        self.btnRename.setText(_translate("Dialog", "Rename"))
        self.btnCopy.setText(_translate("Dialog", "Copy"))
        self.btnDelete.setText(_translate("Dialog", "Delete"))
        self.btnClose.setText(_translate("Dialog", "Close"))
        self.btnnamelistpreset.setText(_translate("Dialog", "Presets"))

import openshot_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

