# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'export-video.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 800)
        Dialog.setMaximumSize(QtCore.QSize(530, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../xdg/openshot.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        Dialog.setAutoFillBackground(False)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lblfilename = QtWidgets.QLineEdit(Dialog)
        self.lblfilename.setObjectName("lblfilename")
        self.gridLayout.addWidget(self.lblfilename, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lbldestination = QtWidgets.QLineEdit(Dialog)
        self.lbldestination.setObjectName("lbldestination")
        self.gridLayout.addWidget(self.lbldestination, 1, 1, 1, 2)
        self.btnfolder = QtWidgets.QPushButton(Dialog)
        icon = QtGui.QIcon.fromTheme("add")
        self.btnfolder.setIcon(icon)
        self.btnfolder.setObjectName("btnfolder")
        self.gridLayout.addWidget(self.btnfolder, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.cbopreset = QtWidgets.QComboBox(Dialog)
        self.cbopreset.setObjectName("cbopreset")
        self.gridLayout.addWidget(self.cbopreset, 2, 1, 1, 3)
        self.btndeletepreset = QtWidgets.QPushButton(Dialog)
        self.btndeletepreset.setObjectName("btndeletepreset")
        self.gridLayout.addWidget(self.btndeletepreset, 3, 1, 1, 1)
        self.btnapplypreset = QtWidgets.QPushButton(Dialog)
        self.btnapplypreset.setObjectName("btnapplypreset")
        self.gridLayout.addWidget(self.btnapplypreset, 3, 2, 1, 2)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabsimple = QtWidgets.QWidget()
        self.tabsimple.setObjectName("tabsimple")
        self.label_16 = QtWidgets.QLabel(self.tabsimple)
        self.label_16.setGeometry(QtCore.QRect(20, 20, 185, 15))
        self.label_16.setObjectName("label_16")
        self.chkentiresequence = QtWidgets.QCheckBox(self.tabsimple)
        self.chkentiresequence.setGeometry(QtCore.QRect(30, 50, 185, 21))
        self.chkentiresequence.setChecked(True)
        self.chkentiresequence.setObjectName("chkentiresequence")
        self.chkoriginalsize = QtWidgets.QCheckBox(self.tabsimple)
        self.chkoriginalsize.setGeometry(QtCore.QRect(30, 240, 185, 21))
        self.chkoriginalsize.setChecked(False)
        self.chkoriginalsize.setObjectName("chkoriginalsize")
        self.label_17 = QtWidgets.QLabel(self.tabsimple)
        self.label_17.setEnabled(False)
        self.label_17.setGeometry(QtCore.QRect(30, 100, 50, 15))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tabsimple)
        self.label_18.setEnabled(False)
        self.label_18.setGeometry(QtCore.QRect(260, 100, 50, 15))
        self.label_18.setObjectName("label_18")
        self.spbfrom = QtWidgets.QTimeEdit(self.tabsimple)
        self.spbfrom.setEnabled(False)
        self.spbfrom.setGeometry(QtCore.QRect(110, 90, 118, 30))
        self.spbfrom.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.spbfrom.setObjectName("spbfrom")
        self.spbto = QtWidgets.QTimeEdit(self.tabsimple)
        self.spbto.setEnabled(False)
        self.spbto.setGeometry(QtCore.QRect(340, 90, 118, 30))
        self.spbto.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.spbto.setObjectName("spbto")
        self.label_19 = QtWidgets.QLabel(self.tabsimple)
        self.label_19.setGeometry(QtCore.QRect(20, 160, 185, 15))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tabsimple)
        self.label_20.setEnabled(False)
        self.label_20.setGeometry(QtCore.QRect(30, 300, 80, 15))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tabsimple)
        self.label_21.setGeometry(QtCore.QRect(290, 300, 80, 15))
        self.label_21.setObjectName("label_21")
        self.spbwidth = QtWidgets.QSpinBox(self.tabsimple)
        self.spbwidth.setEnabled(False)
        self.spbwidth.setGeometry(QtCore.QRect(120, 290, 80, 30))
        self.spbwidth.setMaximum(1920)
        self.spbwidth.setProperty("value", 1280)
        self.spbwidth.setObjectName("spbwidth")
        self.spbheight = QtWidgets.QSpinBox(self.tabsimple)
        self.spbheight.setEnabled(False)
        self.spbheight.setGeometry(QtCore.QRect(380, 290, 80, 30))
        self.spbheight.setMaximum(1200)
        self.spbheight.setProperty("value", 720)
        self.spbheight.setObjectName("spbheight")
        self.btnpreserveratio = QtWidgets.QPushButton(self.tabsimple)
        self.btnpreserveratio.setEnabled(False)
        self.btnpreserveratio.setGeometry(QtCore.QRect(230, 290, 50, 30))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Compass/actions/media-toolbar/media-playlist-repeat.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnpreserveratio.setIcon(icon1)
        self.btnpreserveratio.setIconSize(QtCore.QSize(48, 48))
        self.btnpreserveratio.setObjectName("btnpreserveratio")
        self.label_22 = QtWidgets.QLabel(self.tabsimple)
        self.label_22.setGeometry(QtCore.QRect(20, 370, 185, 15))
        self.label_22.setObjectName("label_22")
        self.cbosqueze = QtWidgets.QComboBox(self.tabsimple)
        self.cbosqueze.setGeometry(QtCore.QRect(230, 360, 231, 30))
        self.cbosqueze.setObjectName("cbosqueze")
        self.cbosqueze.addItem("")
        self.chkprojectprofilesettings = QtWidgets.QCheckBox(self.tabsimple)
        self.chkprojectprofilesettings.setGeometry(QtCore.QRect(30, 190, 431, 21))
        self.chkprojectprofilesettings.setChecked(True)
        self.chkprojectprofilesettings.setObjectName("chkprojectprofilesettings")
        self.label_33 = QtWidgets.QLabel(self.tabsimple)
        self.label_33.setGeometry(QtCore.QRect(20, 420, 185, 15))
        self.label_33.setObjectName("label_33")
        self.chkdirectcopy = QtWidgets.QCheckBox(self.tabsimple)
        self.chkdirectcopy.setGeometry(QtCore.QRect(30, 450, 185, 21))
        self.chkdirectcopy.setChecked(False)
        self.chkdirectcopy.setObjectName("chkdirectcopy")
        self.tabWidget.addTab(self.tabsimple, "")
        self.tabexportaudiovideo = QtWidgets.QWidget()
        self.tabexportaudiovideo.setObjectName("tabexportaudiovideo")
        self.label_15 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_15.setGeometry(QtCore.QRect(20, 20, 91, 16))
        self.label_15.setObjectName("label_15")
        self.cmbformatvideo = QtWidgets.QComboBox(self.tabexportaudiovideo)
        self.cmbformatvideo.setGeometry(QtCore.QRect(130, 10, 341, 30))
        self.cmbformatvideo.setObjectName("cmbformatvideo")
        self.label_23 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_23.setGeometry(QtCore.QRect(20, 70, 171, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_24.setGeometry(QtCore.QRect(20, 120, 171, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_25.setGeometry(QtCore.QRect(20, 170, 171, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_26.setGeometry(QtCore.QRect(20, 220, 171, 15))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_27.setGeometry(QtCore.QRect(20, 370, 171, 15))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_28.setGeometry(QtCore.QRect(20, 420, 171, 15))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_29.setGeometry(QtCore.QRect(20, 470, 171, 15))
        self.label_29.setObjectName("label_29")
        self.sliderbitrate = QtWidgets.QSlider(self.tabexportaudiovideo)
        self.sliderbitrate.setGeometry(QtCore.QRect(20, 550, 441, 24))
        self.sliderbitrate.setMinimum(8)
        self.sliderbitrate.setMaximum(640)
        self.sliderbitrate.setSingleStep(8)
        self.sliderbitrate.setPageStep(1)
        self.sliderbitrate.setSliderPosition(192)
        self.sliderbitrate.setOrientation(QtCore.Qt.Horizontal)
        self.sliderbitrate.setObjectName("sliderbitrate")
        self.label_30 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_30.setGeometry(QtCore.QRect(20, 520, 130, 15))
        self.label_30.setObjectName("label_30")
        self.spbrate = QtWidgets.QSpinBox(self.tabexportaudiovideo)
        self.spbrate.setGeometry(QtCore.QRect(230, 160, 130, 30))
        self.spbrate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spbrate.setObjectName("spbrate")
        self.label_31 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_31.setGeometry(QtCore.QRect(380, 170, 91, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_32.setGeometry(QtCore.QRect(380, 220, 91, 16))
        self.label_32.setObjectName("label_32")
        self.cmbchannels = QtWidgets.QComboBox(self.tabexportaudiovideo)
        self.cmbchannels.setGeometry(QtCore.QRect(230, 460, 240, 30))
        self.cmbchannels.setObjectName("cmbchannels")
        self.cmbaudio = QtWidgets.QComboBox(self.tabexportaudiovideo)
        self.cmbaudio.setGeometry(QtCore.QRect(230, 360, 240, 30))
        self.cmbaudio.setObjectName("cmbaudio")
        self.cmbsimplerate = QtWidgets.QComboBox(self.tabexportaudiovideo)
        self.cmbsimplerate.setGeometry(QtCore.QRect(230, 410, 240, 30))
        self.cmbsimplerate.setObjectName("cmbsimplerate")
        self.cmbvideo = QtWidgets.QComboBox(self.tabexportaudiovideo)
        self.cmbvideo.setGeometry(QtCore.QRect(230, 60, 240, 30))
        self.cmbvideo.setObjectName("cmbvideo")
        self.cmbcompressionmethod = QtWidgets.QComboBox(self.tabexportaudiovideo)
        self.cmbcompressionmethod.setGeometry(QtCore.QRect(230, 110, 240, 30))
        self.cmbcompressionmethod.setObjectName("cmbcompressionmethod")
        self.spbmax = QtWidgets.QSpinBox(self.tabexportaudiovideo)
        self.spbmax.setGeometry(QtCore.QRect(230, 210, 130, 30))
        self.spbmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spbmax.setObjectName("spbmax")
        self.lcdaudiobitrate = QtWidgets.QLCDNumber(self.tabexportaudiovideo)
        self.lcdaudiobitrate.setGeometry(QtCore.QRect(340, 510, 70, 40))
        self.lcdaudiobitrate.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lcdaudiobitrate.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lcdaudiobitrate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdaudiobitrate.setLineWidth(1)
        self.lcdaudiobitrate.setDigitCount(3)
        self.lcdaudiobitrate.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdaudiobitrate.setProperty("intValue", 192)
        self.lcdaudiobitrate.setObjectName("lcdaudiobitrate")
        self.cmbaspectratio = QtWidgets.QComboBox(self.tabexportaudiovideo)
        self.cmbaspectratio.setGeometry(QtCore.QRect(230, 260, 240, 30))
        self.cmbaspectratio.setObjectName("cmbaspectratio")
        self.cmbfps = QtWidgets.QComboBox(self.tabexportaudiovideo)
        self.cmbfps.setGeometry(QtCore.QRect(230, 310, 240, 30))
        self.cmbfps.setObjectName("cmbfps")
        self.label_34 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_34.setGeometry(QtCore.QRect(20, 270, 171, 15))
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tabexportaudiovideo)
        self.label_35.setGeometry(QtCore.QRect(20, 320, 171, 15))
        self.label_35.setObjectName("label_35")
        self.tabWidget.addTab(self.tabexportaudiovideo, "")
        self.tabexportimagesequence = QtWidgets.QWidget()
        self.tabexportimagesequence.setObjectName("tabexportimagesequence")
        self.label_4 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 130, 15))
        self.label_4.setObjectName("label_4")
        self.cmbformatimage = QtWidgets.QComboBox(self.tabexportimagesequence)
        self.cmbformatimage.setGeometry(QtCore.QRect(200, 20, 271, 30))
        self.cmbformatimage.setObjectName("cmbformatimage")
        self.sliderquality = QtWidgets.QSlider(self.tabexportimagesequence)
        self.sliderquality.setGeometry(QtCore.QRect(20, 90, 441, 24))
        self.sliderquality.setMaximum(100)
        self.sliderquality.setSliderPosition(85)
        self.sliderquality.setOrientation(QtCore.Qt.Horizontal)
        self.sliderquality.setObjectName("sliderquality")
        self.label_5 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 130, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_6.setGeometry(QtCore.QRect(20, 130, 130, 15))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_7.setGeometry(QtCore.QRect(330, 130, 130, 15))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_8.setGeometry(QtCore.QRect(20, 170, 185, 15))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_9.setGeometry(QtCore.QRect(30, 210, 130, 15))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_10.setGeometry(QtCore.QRect(190, 210, 101, 16))
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_11.setGeometry(QtCore.QRect(340, 210, 111, 16))
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.lblprefix = QtWidgets.QLineEdit(self.tabexportimagesequence)
        self.lblprefix.setGeometry(QtCore.QRect(20, 240, 130, 30))
        self.lblprefix.setObjectName("lblprefix")
        self.lblsuffix = QtWidgets.QLineEdit(self.tabexportimagesequence)
        self.lblsuffix.setGeometry(QtCore.QRect(340, 240, 130, 30))
        self.lblsuffix.setObjectName("lblsuffix")
        self.label_12 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_12.setGeometry(QtCore.QRect(20, 310, 100, 15))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_13.setGeometry(QtCore.QRect(250, 310, 100, 15))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tabexportimagesequence)
        self.label_14.setGeometry(QtCore.QRect(20, 360, 160, 15))
        self.label_14.setObjectName("label_14")
        self.lblframename = QtWidgets.QLabel(self.tabexportimagesequence)
        self.lblframename.setGeometry(QtCore.QRect(200, 360, 250, 15))
        self.lblframename.setObjectName("lblframename")
        self.spbinterval = QtWidgets.QSpinBox(self.tabexportimagesequence)
        self.spbinterval.setGeometry(QtCore.QRect(140, 300, 100, 30))
        self.spbinterval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spbinterval.setProperty("value", 1)
        self.spbinterval.setObjectName("spbinterval")
        self.spboffset = QtWidgets.QSpinBox(self.tabexportimagesequence)
        self.spboffset.setGeometry(QtCore.QRect(370, 300, 100, 30))
        self.spboffset.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spboffset.setObjectName("spboffset")
        self.spbdigits = QtWidgets.QSpinBox(self.tabexportimagesequence)
        self.spbdigits.setGeometry(QtCore.QRect(190, 240, 100, 30))
        self.spbdigits.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spbdigits.setMaximum(9900000)
        self.spbdigits.setObjectName("spbdigits")
        self.tabWidget.addTab(self.tabexportimagesequence, "")
        self.tabadvanced = QtWidgets.QWidget()
        self.tabadvanced.setObjectName("tabadvanced")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tabadvanced)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 461, 401))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.btnloadffmpegcommand = QtWidgets.QPushButton(self.tabadvanced)
        self.btnloadffmpegcommand.setGeometry(QtCore.QRect(30, 440, 160, 30))
        self.btnloadffmpegcommand.setObjectName("btnloadffmpegcommand")
        self.btnexportcommand = QtWidgets.QPushButton(self.tabadvanced)
        self.btnexportcommand.setGeometry(QtCore.QRect(290, 440, 160, 30))
        self.btnexportcommand.setObjectName("btnexportcommand")
        self.tabWidget.addTab(self.tabadvanced, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout.addWidget(self.widget, 4, 0, 1, 4)
        self.btncancel = QtWidgets.QPushButton(Dialog)
        self.btncancel.setObjectName("btncancel")
        self.gridLayout.addWidget(self.btncancel, 5, 1, 1, 1)
        self.btnexport = QtWidgets.QPushButton(Dialog)
        self.btnexport.setObjectName("btnexport")
        self.gridLayout.addWidget(self.btnexport, 5, 2, 1, 2)
        self.cmbextension = QtWidgets.QComboBox(Dialog)
        self.cmbextension.setObjectName("cmbextension")
        self.gridLayout.addWidget(self.cmbextension, 0, 3, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.btncancel.clicked.connect(Dialog.reject)
        self.btnexport.clicked.connect(Dialog.accept)
        self.sliderbitrate.valueChanged['int'].connect(self.lcdaudiobitrate.display)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Export Video"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p>File Name:</p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p>Destination:</p></body></html>"))
        self.btnfolder.setText(_translate("Dialog", "Add"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p>Preset:</p></body></html>"))
        self.btndeletepreset.setText(_translate("Dialog", "Delete Preset"))
        self.btnapplypreset.setText(_translate("Dialog", "Apply Preset"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Lenght:</span></p></body></html>"))
        self.chkentiresequence.setText(_translate("Dialog", "Entire Sequence"))
        self.chkoriginalsize.setText(_translate("Dialog", "Original Size"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p>From:</p></body></html>"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p>To:</p></body></html>"))
        self.spbfrom.setDisplayFormat(_translate("Dialog", "HH:mm:ss:ms"))
        self.spbto.setDisplayFormat(_translate("Dialog", "HH:mm:ss:ms"))
        self.label_19.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Dimensions:</span></p></body></html>"))
        self.label_20.setText(_translate("Dialog", "<html><head/><body><p>Width:</p></body></html>"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p>Height:</p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p>Scale Method:</p></body></html>"))
        self.cbosqueze.setItemText(0, _translate("Dialog", "Squeze"))
        self.chkprojectprofilesettings.setText(_translate("Dialog", "Use Project Profile Settings"))
        self.label_33.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Direct Copy:</span></p></body></html>"))
        self.chkdirectcopy.setText(_translate("Dialog", "Entire Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabsimple), _translate("Dialog", "Source"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Format:</span></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Video Codec:</span></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p>Compression Method:</p></body></html>"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p>BitRate:</p></body></html>"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p>Max Bitrate:</p></body></html>"))
        self.label_27.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Audio Codec:</span></p></body></html>"))
        self.label_28.setText(_translate("Dialog", "<html><head/><body><p>Simple Rate:</p></body></html>"))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p>Channels:</p></body></html>"))
        self.label_30.setText(_translate("Dialog", "<html><head/><body><p>Bit Rate (kbps):</p></body></html>"))
        self.label_31.setText(_translate("Dialog", "<html><head/><body><p>kbps</p></body></html>"))
        self.label_32.setText(_translate("Dialog", "<html><head/><body><p>kbps</p></body></html>"))
        self.label_34.setText(_translate("Dialog", "Aspect Ratio:"))
        self.label_35.setText(_translate("Dialog", "Frames per Second:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabexportaudiovideo), _translate("Dialog", "Ouput Audio/Video"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Format:</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p>Quality (%): </p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:7pt;\">Lowest</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:7pt;\">Highest</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">File Naming:</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p>Prefix:</p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p>Digits:</p></body></html>"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p>Suffix:</p></body></html>"))
        self.lblprefix.setText(_translate("Dialog", "image_"))
        self.lblsuffix.setText(_translate("Dialog", ".resiszed"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p>Interval:</p></body></html>"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p>Offset:</p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p>First Frame Name:</p></body></html>"))
        self.lblframename.setText(_translate("Dialog", "<html><head/><body><p>image_00001.resized</p></body></html>"))
        self.spbdigits.setSuffix(_translate("Dialog", "000"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabexportimagesequence), _translate("Dialog", "Export Image Sequence"))
        self.btnloadffmpegcommand.setText(_translate("Dialog", "Load render args"))
        self.btnexportcommand.setText(_translate("Dialog", "Create Profile args"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabadvanced), _translate("Dialog", "Advanced"))
        self.btncancel.setText(_translate("Dialog", "Cancel"))
        self.btnexport.setText(_translate("Dialog", "Export"))

import openshot_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

