# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file-properties.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 900)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.btnapply = QtWidgets.QPushButton(Dialog)
        self.btnapply.setGeometry(QtCore.QRect(420, 830, 151, 41))
        self.btnapply.setObjectName("btnapply")
        self.btnclose = QtWidgets.QPushButton(Dialog)
        self.btnclose.setGeometry(QtCore.QRect(240, 830, 151, 41))
        self.btnclose.setObjectName("btnclose")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(60, 30, 120, 25))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 80, 120, 25))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(20, 120, 560, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(60, 140, 471, 301))
        self.graphicsView.setObjectName("graphicsView")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(20, 450, 560, 3))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(30, 750, 550, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(300, 450, 20, 300))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 780, 120, 25))
        self.label_5.setObjectName("label_5")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_3.setGeometry(QtCore.QRect(210, 772, 351, 41))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 460, 120, 25))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 510, 120, 25))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(40, 560, 120, 25))
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 610, 120, 25))
        self.label_2.setObjectName("label_2")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(40, 670, 120, 25))
        self.label_12.setObjectName("label_12")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(40, 720, 131, 25))
        self.label_24.setObjectName("label_24")
        self.lbltypefile = QtWidgets.QLabel(Dialog)
        self.lbltypefile.setGeometry(QtCore.QRect(330, 460, 120, 25))
        self.lbltypefile.setObjectName("lbltypefile")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(330, 510, 120, 25))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(330, 560, 132, 25))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(330, 610, 120, 25))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(330, 670, 120, 25))
        self.label_11.setObjectName("label_11")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(330, 720, 120, 25))
        self.label_26.setObjectName("label_26")
        self.lblformat = QtWidgets.QLabel(Dialog)
        self.lblformat.setGeometry(QtCore.QRect(190, 460, 100, 25))
        self.lblformat.setObjectName("lblformat")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(480, 460, 100, 25))
        self.label_15.setObjectName("label_15")
        self.lblsize = QtWidgets.QLabel(Dialog)
        self.lblsize.setGeometry(QtCore.QRect(190, 510, 100, 25))
        self.lblsize.setObjectName("lblsize")
        self.lbllenght = QtWidgets.QLabel(Dialog)
        self.lbllenght.setGeometry(QtCore.QRect(190, 560, 100, 25))
        self.lbllenght.setObjectName("lbllenght")
        self.lblvideocodec = QtWidgets.QLabel(Dialog)
        self.lblvideocodec.setGeometry(QtCore.QRect(190, 610, 100, 25))
        self.lblvideocodec.setObjectName("lblvideocodec")
        self.lblvideobitrate = QtWidgets.QLabel(Dialog)
        self.lblvideobitrate.setGeometry(QtCore.QRect(190, 670, 100, 25))
        self.lblvideobitrate.setObjectName("lblvideobitrate")
        self.lblratio = QtWidgets.QLabel(Dialog)
        self.lblratio.setGeometry(QtCore.QRect(190, 720, 100, 25))
        self.lblratio.setAlignment(QtCore.Qt.AlignCenter)
        self.lblratio.setObjectName("lblratio")
        self.lblaudio = QtWidgets.QLabel(Dialog)
        self.lblaudio.setGeometry(QtCore.QRect(480, 510, 100, 25))
        self.lblaudio.setObjectName("lblaudio")
        self.lblaudiosamplerate = QtWidgets.QLabel(Dialog)
        self.lblaudiosamplerate.setGeometry(QtCore.QRect(480, 560, 100, 25))
        self.lblaudiosamplerate.setObjectName("lblaudiosamplerate")
        self.lblaudiochannels = QtWidgets.QLabel(Dialog)
        self.lblaudiochannels.setGeometry(QtCore.QRect(480, 610, 100, 25))
        self.lblaudiochannels.setAlignment(QtCore.Qt.AlignCenter)
        self.lblaudiochannels.setObjectName("lblaudiochannels")
        self.lblaudiobitrate = QtWidgets.QLabel(Dialog)
        self.lblaudiobitrate.setGeometry(QtCore.QRect(480, 670, 100, 25))
        self.lblaudiobitrate.setObjectName("lblaudiobitrate")
        self.lblframerate = QtWidgets.QLabel(Dialog)
        self.lblframerate.setGeometry(QtCore.QRect(480, 720, 100, 25))
        self.lblframerate.setAlignment(QtCore.Qt.AlignCenter)
        self.lblframerate.setObjectName("lblframerate")
        self.lnelabel = QtWidgets.QLineEdit(Dialog)
        self.lnelabel.setGeometry(QtCore.QRect(210, 20, 350, 41))
        self.lnelabel.setObjectName("lnelabel")
        self.lnefilename = QtWidgets.QLineEdit(Dialog)
        self.lnefilename.setGeometry(QtCore.QRect(210, 70, 350, 41))
        self.lnefilename.setObjectName("lnefilename")

        self.retranslateUi(Dialog)
        self.btnapply.clicked.connect(Dialog.accept)
        self.btnclose.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnapply.setText(_translate("Dialog", "Apply"))
        self.btnclose.setText(_translate("Dialog", "Close"))
        self.label_13.setText(_translate("Dialog", "Label:"))
        self.label.setText(_translate("Dialog", "File Name:"))
        self.label_5.setText(_translate("Dialog", "Path file :"))
        self.label_4.setText(_translate("Dialog", "Format Video : "))
        self.label_6.setText(_translate("Dialog", "Size File :"))
        self.label_7.setText(_translate("Dialog", "Lenght File : "))
        self.label_2.setText(_translate("Dialog", "Video Codec :"))
        self.label_12.setText(_translate("Dialog", "Video Bitrate :"))
        self.label_24.setText(_translate("Dialog", "Aspect Ratio :"))
        self.lbltypefile.setText(_translate("Dialog", "Type File : "))
        self.label_8.setText(_translate("Dialog", "Audio Codec :"))
        self.label_9.setText(_translate("Dialog", "Audio Sample Rate :"))
        self.label_10.setText(_translate("Dialog", "Audio Channels :"))
        self.label_11.setText(_translate("Dialog", "Audio Bitrate :"))
        self.label_26.setText(_translate("Dialog", "Framerate :"))
        self.lblformat.setText(_translate("Dialog", "MKV / .mkv"))
        self.label_15.setText(_translate("Dialog", "Video"))
        self.lblsize.setText(_translate("Dialog", "1280 x 720"))
        self.lbllenght.setText(_translate("Dialog", "00:23:27:239"))
        self.lblvideocodec.setText(_translate("Dialog", "MPEG-4 AVC"))
        self.lblvideobitrate.setText(_translate("Dialog", "8600 k/bts"))
        self.lblratio.setText(_translate("Dialog", "16:9"))
        self.lblaudio.setText(_translate("Dialog", "FLAC / .flac"))
        self.lblaudiosamplerate.setText(_translate("Dialog", "48000 Hz"))
        self.lblaudiochannels.setText(_translate("Dialog", "2"))
        self.lblaudiobitrate.setText(_translate("Dialog", "192 k/bts"))
        self.lblframerate.setText(_translate("Dialog", "25.0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

