# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simplekeyframeeditor.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(500, 760)
        DockWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.label_13 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 80, 15))
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_23 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_23.setGeometry(QtCore.QRect(400, 620, 80, 15))
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_16 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(10, 620, 80, 15))
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.label_15 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(120, 620, 80, 15))
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(240, 620, 40, 15))
        self.label_14.setObjectName("label_14")
        self.label_22 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_22.setGeometry(QtCore.QRect(340, 620, 40, 15))
        self.label_22.setObjectName("label_22")
        self.cmbkeyimage = QtWidgets.QComboBox(self.dockWidgetContents)
        self.cmbkeyimage.setGeometry(QtCore.QRect(120, 20, 360, 30))
        self.cmbkeyimage.setObjectName("cmbkeyimage")
        self.btncancel = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btncancel.setGeometry(QtCore.QRect(60, 670, 140, 40))
        self.btncancel.setObjectName("btncancel")
        self.btnapply = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btnapply.setGeometry(QtCore.QRect(290, 670, 140, 40))
        self.btnapply.setObjectName("btnapply")
        self.sliderheight = QtWidgets.QSlider(self.dockWidgetContents)
        self.sliderheight.setGeometry(QtCore.QRect(30, 210, 30, 380))
        self.sliderheight.setMaximum(300)
        self.sliderheight.setProperty("value", 100)
        self.sliderheight.setOrientation(QtCore.Qt.Vertical)
        self.sliderheight.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.sliderheight.setObjectName("sliderheight")
        self.lcdheight = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdheight.setGeometry(QtCore.QRect(10, 140, 70, 40))
        self.lcdheight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdheight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lcdheight.setLineWidth(1)
        self.lcdheight.setMidLineWidth(0)
        self.lcdheight.setDigitCount(3)
        self.lcdheight.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdheight.setProperty("value", 100.0)
        self.lcdheight.setObjectName("lcdheight")
        self.sliderweight = QtWidgets.QSlider(self.dockWidgetContents)
        self.sliderweight.setGeometry(QtCore.QRect(130, 210, 30, 380))
        self.sliderweight.setMaximum(300)
        self.sliderweight.setProperty("value", 100)
        self.sliderweight.setOrientation(QtCore.Qt.Vertical)
        self.sliderweight.setObjectName("sliderweight")
        self.lcdweight = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdweight.setGeometry(QtCore.QRect(110, 140, 70, 40))
        self.lcdweight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdweight.setDigitCount(3)
        self.lcdweight.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdweight.setProperty("value", 100.0)
        self.lcdweight.setObjectName("lcdweight")
        self.sliderx = QtWidgets.QSlider(self.dockWidgetContents)
        self.sliderx.setGeometry(QtCore.QRect(230, 210, 30, 380))
        self.sliderx.setMaximum(100)
        self.sliderx.setSingleStep(1)
        self.sliderx.setOrientation(QtCore.Qt.Vertical)
        self.sliderx.setObjectName("sliderx")
        self.lcdx = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdx.setGeometry(QtCore.QRect(210, 140, 70, 40))
        self.lcdx.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdx.setDigitCount(3)
        self.lcdx.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdx.setObjectName("lcdx")
        self.slidery = QtWidgets.QSlider(self.dockWidgetContents)
        self.slidery.setGeometry(QtCore.QRect(330, 210, 30, 380))
        self.slidery.setMaximum(100)
        self.slidery.setOrientation(QtCore.Qt.Vertical)
        self.slidery.setObjectName("slidery")
        self.lcdy = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdy.setGeometry(QtCore.QRect(310, 140, 70, 40))
        self.lcdy.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdy.setMidLineWidth(0)
        self.lcdy.setDigitCount(3)
        self.lcdy.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdy.setObjectName("lcdy")
        self.slideralpha = QtWidgets.QSlider(self.dockWidgetContents)
        self.slideralpha.setGeometry(QtCore.QRect(430, 210, 30, 380))
        self.slideralpha.setMaximum(100)
        self.slideralpha.setProperty("value", 100)
        self.slideralpha.setOrientation(QtCore.Qt.Vertical)
        self.slideralpha.setObjectName("slideralpha")
        self.lcdalpha = QtWidgets.QLCDNumber(self.dockWidgetContents)
        self.lcdalpha.setGeometry(QtCore.QRect(410, 140, 70, 40))
        self.lcdalpha.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lcdalpha.setLineWidth(1)
        self.lcdalpha.setDigitCount(3)
        self.lcdalpha.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdalpha.setProperty("value", 100.0)
        self.lcdalpha.setObjectName("lcdalpha")
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        self.btncancel.clicked.connect(DockWidget.close)
        self.sliderheight.valueChanged['int'].connect(self.lcdheight.display)
        self.sliderweight.valueChanged['int'].connect(self.lcdweight.display)
        self.sliderx.valueChanged['int'].connect(self.lcdx.display)
        self.slidery.valueChanged['int'].connect(self.lcdy.display)
        self.slideralpha.valueChanged['int'].connect(self.lcdalpha.display)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "Simple Keyframe Editor"))
        self.label_13.setText(_translate("DockWidget", "<html><head/><body><p>Key Frame:</p></body></html>"))
        self.label_23.setText(_translate("DockWidget", "<html><head/><body><p>Alpha:</p></body></html>"))
        self.label_16.setText(_translate("DockWidget", "<html><head/><body><p>Height:</p></body></html>"))
        self.label_15.setText(_translate("DockWidget", "<html><head/><body><p>Weight:</p></body></html>"))
        self.label_14.setText(_translate("DockWidget", "<html><head/><body><p>X:</p></body></html>"))
        self.label_22.setText(_translate("DockWidget", "<html><head/><body><p>Y:</p></body></html>"))
        self.btncancel.setText(_translate("DockWidget", "Cancel"))
        self.btnapply.setText(_translate("DockWidget", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DockWidget = QtWidgets.QDockWidget()
    ui = Ui_DockWidget()
    ui.setupUi(DockWidget)
    DockWidget.show()
    sys.exit(app.exec_())

