# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'estabilize.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 750)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblnamefiletransformed = QtWidgets.QLabel(Dialog)
        self.lblnamefiletransformed.setMinimumSize(QtCore.QSize(250, 30))
        self.lblnamefiletransformed.setObjectName("lblnamefiletransformed")
        self.horizontalLayout_3.addWidget(self.lblnamefiletransformed)
        self.lnenamefiletransformed = QtWidgets.QLineEdit(Dialog)
        self.lnenamefiletransformed.setMinimumSize(QtCore.QSize(330, 33))
        self.lnenamefiletransformed.setObjectName("lnenamefiletransformed")
        self.horizontalLayout_3.addWidget(self.lnenamefiletransformed)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lneinmputfile = QtWidgets.QLineEdit(Dialog)
        self.lneinmputfile.setMinimumSize(QtCore.QSize(410, 33))
        self.lneinmputfile.setObjectName("lneinmputfile")
        self.gridLayout.addWidget(self.lneinmputfile, 0, 0, 1, 1)
        self.btninputfile = QtWidgets.QPushButton(Dialog)
        self.btninputfile.setMinimumSize(QtCore.QSize(175, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/folder-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btninputfile.setIcon(icon)
        self.btninputfile.setIconSize(QtCore.QSize(32, 32))
        self.btninputfile.setObjectName("btninputfile")
        self.gridLayout.addWidget(self.btninputfile, 0, 1, 1, 1)
        self.lnefileoutput = QtWidgets.QLineEdit(Dialog)
        self.lnefileoutput.setMinimumSize(QtCore.QSize(410, 33))
        self.lnefileoutput.setObjectName("lnefileoutput")
        self.gridLayout.addWidget(self.lnefileoutput, 1, 0, 1, 1)
        self.btnoutputfile = QtWidgets.QPushButton(Dialog)
        self.btnoutputfile.setMinimumSize(QtCore.QSize(175, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../.designer/backup/folder-violet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnoutputfile.setIcon(icon1)
        self.btnoutputfile.setIconSize(QtCore.QSize(32, 32))
        self.btnoutputfile.setObjectName("btnoutputfile")
        self.gridLayout.addWidget(self.btnoutputfile, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setMinimumSize(QtCore.QSize(450, 33))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.btnrender = QtWidgets.QPushButton(Dialog)
        self.btnrender.setMinimumSize(QtCore.QSize(135, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../.designer/backup/tools-media-optical-burn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnrender.setIcon(icon2)
        self.btnrender.setIconSize(QtCore.QSize(32, 32))
        self.btnrender.setObjectName("btnrender")
        self.horizontalLayout_4.addWidget(self.btnrender)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setObjectName("tabWidget")
        self.tbstabilize = QtWidgets.QWidget()
        self.tbstabilize.setObjectName("tbstabilize")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tbstabilize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.tbstabilize)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblmaxshift = QtWidgets.QLabel(self.frame_2)
        self.lblmaxshift.setMinimumSize(QtCore.QSize(150, 20))
        self.lblmaxshift.setObjectName("lblmaxshift")
        self.horizontalLayout_2.addWidget(self.lblmaxshift)
        self.slidermaxshift = QtWidgets.QSlider(self.frame_2)
        self.slidermaxshift.setMinimumSize(QtCore.QSize(370, 25))
        self.slidermaxshift.setMinimum(1)
        self.slidermaxshift.setMaximum(100)
        self.slidermaxshift.setProperty("value", 48)
        self.slidermaxshift.setSliderPosition(48)
        self.slidermaxshift.setOrientation(QtCore.Qt.Horizontal)
        self.slidermaxshift.setObjectName("slidermaxshift")
        self.horizontalLayout_2.addWidget(self.slidermaxshift)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblstepsize = QtWidgets.QLabel(self.frame_2)
        self.lblstepsize.setMinimumSize(QtCore.QSize(150, 20))
        self.lblstepsize.setObjectName("lblstepsize")
        self.horizontalLayout_5.addWidget(self.lblstepsize)
        self.sliderstepsize = QtWidgets.QSlider(self.frame_2)
        self.sliderstepsize.setMinimumSize(QtCore.QSize(370, 25))
        self.sliderstepsize.setMinimum(1)
        self.sliderstepsize.setMaximum(100)
        self.sliderstepsize.setProperty("value", 2)
        self.sliderstepsize.setSliderPosition(2)
        self.sliderstepsize.setOrientation(QtCore.Qt.Horizontal)
        self.sliderstepsize.setObjectName("sliderstepsize")
        self.horizontalLayout_5.addWidget(self.sliderstepsize)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblallowmax = QtWidgets.QLabel(self.frame_2)
        self.lblallowmax.setMinimumSize(QtCore.QSize(110, 20))
        self.lblallowmax.setObjectName("lblallowmax")
        self.gridLayout_2.addWidget(self.lblallowmax, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setMinimumSize(QtCore.QSize(141, 33))
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 0, 1, 1, 1)
        self.lblalgo = QtWidgets.QLabel(self.frame_2)
        self.lblalgo.setMinimumSize(QtCore.QSize(110, 20))
        self.lblalgo.setObjectName("lblalgo")
        self.gridLayout_2.addWidget(self.lblalgo, 0, 2, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_2.setMinimumSize(QtCore.QSize(141, 33))
        self.spinBox_2.setProperty("value", 1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 0, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lblfieldsetup = QtWidgets.QLabel(self.frame_2)
        self.lblfieldsetup.setMinimumSize(QtCore.QSize(150, 20))
        self.lblfieldsetup.setObjectName("lblfieldsetup")
        self.horizontalLayout_8.addWidget(self.lblfieldsetup)
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setMinimumSize(QtCore.QSize(360, 40))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_8.addWidget(self.comboBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblsize = QtWidgets.QLabel(self.frame_2)
        self.lblsize.setMinimumSize(QtCore.QSize(150, 20))
        self.lblsize.setObjectName("lblsize")
        self.horizontalLayout_6.addWidget(self.lblsize)
        self.slidersize = QtWidgets.QSlider(self.frame_2)
        self.slidersize.setMinimumSize(QtCore.QSize(370, 25))
        self.slidersize.setMinimum(1)
        self.slidersize.setMaximum(5)
        self.slidersize.setSliderPosition(3)
        self.slidersize.setOrientation(QtCore.Qt.Horizontal)
        self.slidersize.setObjectName("slidersize")
        self.horizontalLayout_6.addWidget(self.slidersize)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lblfieldsize = QtWidgets.QLabel(self.frame_2)
        self.lblfieldsize.setMinimumSize(QtCore.QSize(150, 20))
        self.lblfieldsize.setObjectName("lblfieldsize")
        self.horizontalLayout_7.addWidget(self.lblfieldsize)
        self.sliderfieldsize = QtWidgets.QSlider(self.frame_2)
        self.sliderfieldsize.setMinimumSize(QtCore.QSize(370, 25))
        self.sliderfieldsize.setMinimum(1)
        self.sliderfieldsize.setMaximum(5)
        self.sliderfieldsize.setSliderPosition(3)
        self.sliderfieldsize.setOrientation(QtCore.Qt.Horizontal)
        self.sliderfieldsize.setObjectName("sliderfieldsize")
        self.horizontalLayout_7.addWidget(self.sliderfieldsize)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tbstabilize, "")
        self.tbtransform = QtWidgets.QWidget()
        self.tbtransform.setObjectName("tbtransform")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tbtransform)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.tbtransform)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lbllissage = QtWidgets.QLabel(self.frame_3)
        self.lbllissage.setMinimumSize(QtCore.QSize(150, 20))
        self.lbllissage.setObjectName("lbllissage")
        self.horizontalLayout_9.addWidget(self.lbllissage)
        self.sliderlissage = QtWidgets.QSlider(self.frame_3)
        self.sliderlissage.setMinimumSize(QtCore.QSize(370, 30))
        self.sliderlissage.setMinimum(1)
        self.sliderlissage.setMaximum(100)
        self.sliderlissage.setSliderPosition(10)
        self.sliderlissage.setOrientation(QtCore.Qt.Horizontal)
        self.sliderlissage.setObjectName("sliderlissage")
        self.horizontalLayout_9.addWidget(self.sliderlissage)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.lblmaxshift_2 = QtWidgets.QLabel(self.frame_3)
        self.lblmaxshift_2.setMinimumSize(QtCore.QSize(150, 20))
        self.lblmaxshift_2.setObjectName("lblmaxshift_2")
        self.horizontalLayout_10.addWidget(self.lblmaxshift_2)
        self.slidermaxshieft_2 = QtWidgets.QSlider(self.frame_3)
        self.slidermaxshieft_2.setMinimumSize(QtCore.QSize(370, 30))
        self.slidermaxshieft_2.setMinimum(1)
        self.slidermaxshieft_2.setMaximum(100)
        self.slidermaxshieft_2.setOrientation(QtCore.Qt.Horizontal)
        self.slidermaxshieft_2.setObjectName("slidermaxshieft_2")
        self.horizontalLayout_10.addWidget(self.slidermaxshieft_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_10)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblcrop = QtWidgets.QLabel(self.frame_3)
        self.lblcrop.setMinimumSize(QtCore.QSize(150, 20))
        self.lblcrop.setObjectName("lblcrop")
        self.gridLayout_3.addWidget(self.lblcrop, 0, 0, 1, 1)
        self.lblmaxangle = QtWidgets.QLabel(self.frame_3)
        self.lblmaxangle.setMinimumSize(QtCore.QSize(150, 20))
        self.lblmaxangle.setObjectName("lblmaxangle")
        self.gridLayout_3.addWidget(self.lblmaxangle, 0, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_2.setMinimumSize(QtCore.QSize(260, 40))
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_3.setMinimumSize(QtCore.QSize(260, 40))
        self.spinBox_3.setProperty("value", 10)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_3.addWidget(self.spinBox_3, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblinvert = QtWidgets.QLabel(self.frame_3)
        self.lblinvert.setMinimumSize(QtCore.QSize(150, 20))
        self.lblinvert.setObjectName("lblinvert")
        self.gridLayout_4.addWidget(self.lblinvert, 0, 0, 1, 1)
        self.lblrelative = QtWidgets.QLabel(self.frame_3)
        self.lblrelative.setMinimumSize(QtCore.QSize(150, 20))
        self.lblrelative.setObjectName("lblrelative")
        self.gridLayout_4.addWidget(self.lblrelative, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(260, 40))
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_4.addWidget(self.comboBox_3, 1, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_4.setMinimumSize(QtCore.QSize(260, 40))
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_4.addWidget(self.comboBox_4, 1, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.tabWidget.addTab(self.tbtransform, "")
        self.tbconsole = QtWidgets.QWidget()
        self.tbconsole.setObjectName("tbconsole")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tbconsole)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(self.tbconsole)
        self.textEdit.setAutoFillBackground(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.tabWidget.addTab(self.tbconsole, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnhelp = QtWidgets.QPushButton(Dialog)
        self.btnhelp.setMinimumSize(QtCore.QSize(140, 33))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../.designer/backup/system-help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnhelp.setIcon(icon3)
        self.btnhelp.setIconSize(QtCore.QSize(24, 24))
        self.btnhelp.setObjectName("btnhelp")
        self.horizontalLayout.addWidget(self.btnhelp)
        spacerItem = QtWidgets.QSpacerItem(248, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setMinimumSize(QtCore.QSize(140, 33))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../.designer/backup/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_4.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblnamefiletransformed.setText(_translate("Dialog", "Name File Transformed :"))
        self.btninputfile.setText(_translate("Dialog", "Input File"))
        self.btnoutputfile.setText(_translate("Dialog", "Output File"))
        self.btnrender.setText(_translate("Dialog", "Render"))
        self.lblmaxshift.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Maxshift:</span></p></body></html>"))
        self.lblstepsize.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Stepsize:</span></p></body></html>"))
        self.lblallowmax.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Allowmax:</span></p></body></html>"))
        self.lblalgo.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Algo:</span></p></body></html>"))
        self.lblfieldsetup.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Fieldsetup:</span></p></body></html>"))
        self.lblsize.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Size:</span></p></body></html>"))
        self.lblfieldsize.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Fieldsize:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbstabilize), _translate("Dialog", "Stabilize"))
        self.lbllissage.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Lissage :</span></p></body></html>"))
        self.lblmaxshift_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Maxshift:</span></p></body></html>"))
        self.lblcrop.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Crop :</span></p></body></html>"))
        self.lblmaxangle.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Maxangle</span></p></body></html>"))
        self.lblinvert.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Invert:</span></p></body></html>"))
        self.lblrelative.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Relative:</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbtransform), _translate("Dialog", "Transform"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbconsole), _translate("Dialog", "Console"))
        self.btnhelp.setText(_translate("Dialog", "Help"))
        self.pushButton_4.setText(_translate("Dialog", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

