# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mx5000.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MX5000(object):
    def setupUi(self, MX5000):
        MX5000.setObjectName("MX5000")
        MX5000.resize(621, 800)
        MX5000.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(MX5000)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(MX5000)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabmain = QtWidgets.QWidget()
        self.tabmain.setObjectName("tabmain")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.tabmain)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame = QtWidgets.QFrame(self.tabmain)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblmails = QtWidgets.QLabel(self.groupBox)
        self.lblmails.setObjectName("lblmails")
        self.horizontalLayout_3.addWidget(self.lblmails)
        self.btnchecknowmails = QtWidgets.QPushButton(self.groupBox)
        self.btnchecknowmails.setMinimumSize(QtCore.QSize(200, 45))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/system-log-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnchecknowmails.setIcon(icon)
        self.btnchecknowmails.setIconSize(QtCore.QSize(48, 48))
        self.btnchecknowmails.setObjectName("btnchecknowmails")
        self.horizontalLayout_3.addWidget(self.btnchecknowmails)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbllog = QtWidgets.QLabel(self.groupBox_2)
        self.lbllog.setObjectName("lbllog")
        self.horizontalLayout_4.addWidget(self.lbllog)
        self.btnclearlog = QtWidgets.QPushButton(self.groupBox_2)
        self.btnclearlog.setMinimumSize(QtCore.QSize(200, 45))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/system-reboot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnclearlog.setIcon(icon1)
        self.btnclearlog.setIconSize(QtCore.QSize(48, 48))
        self.btnclearlog.setObjectName("btnclearlog")
        self.horizontalLayout_4.addWidget(self.btnclearlog)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblkeyboard = QtWidgets.QLabel(self.groupBox_3)
        self.lblkeyboard.setObjectName("lblkeyboard")
        self.horizontalLayout_2.addWidget(self.lblkeyboard)
        self.btnresetkeyboard = QtWidgets.QPushButton(self.groupBox_3)
        self.btnresetkeyboard.setMinimumSize(QtCore.QSize(200, 45))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/system-switch-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnresetkeyboard.setIcon(icon2)
        self.btnresetkeyboard.setIconSize(QtCore.QSize(48, 48))
        self.btnresetkeyboard.setObjectName("btnresetkeyboard")
        self.horizontalLayout_2.addWidget(self.btnresetkeyboard)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_11.addWidget(self.frame)
        self.tabWidget.addTab(self.tabmain, "")
        self.tabsettings = QtWidgets.QWidget()
        self.tabsettings.setObjectName("tabsettings")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.tabsettings)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_2 = QtWidgets.QFrame(self.tabsettings)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(551, 101))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName("gridLayout")
        self.lblpathkeyboard = QtWidgets.QLabel(self.groupBox_4)
        self.lblpathkeyboard.setObjectName("lblpathkeyboard")
        self.gridLayout.addWidget(self.lblpathkeyboard, 0, 0, 1, 1)
        self.lnepathkeyboard = QtWidgets.QLineEdit(self.groupBox_4)
        self.lnepathkeyboard.setObjectName("lnepathkeyboard")
        self.gridLayout.addWidget(self.lnepathkeyboard, 0, 1, 1, 2)
        self.lblnamekeyboard = QtWidgets.QLabel(self.groupBox_4)
        self.lblnamekeyboard.setObjectName("lblnamekeyboard")
        self.gridLayout.addWidget(self.lblnamekeyboard, 1, 0, 1, 2)
        self.lnenamekeyboard = QtWidgets.QLineEdit(self.groupBox_4)
        self.lnenamekeyboard.setObjectName("lnenamekeyboard")
        self.gridLayout.addWidget(self.lnenamekeyboard, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setMinimumSize(QtCore.QSize(551, 531))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblservertype = QtWidgets.QLabel(self.groupBox_5)
        self.lblservertype.setObjectName("lblservertype")
        self.gridLayout_2.addWidget(self.lblservertype, 0, 0, 1, 1)
        self.rdbimap = QtWidgets.QRadioButton(self.groupBox_5)
        self.rdbimap.setObjectName("rdbimap")
        self.gridLayout_2.addWidget(self.rdbimap, 0, 1, 1, 1)
        self.rdbpop = QtWidgets.QRadioButton(self.groupBox_5)
        self.rdbpop.setObjectName("rdbpop")
        self.gridLayout_2.addWidget(self.rdbpop, 0, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblserveradress = QtWidgets.QLabel(self.groupBox_5)
        self.lblserveradress.setObjectName("lblserveradress")
        self.gridLayout_3.addWidget(self.lblserveradress, 0, 0, 1, 1)
        self.lneserveradress = QtWidgets.QLineEdit(self.groupBox_5)
        self.lneserveradress.setObjectName("lneserveradress")
        self.gridLayout_3.addWidget(self.lneserveradress, 0, 1, 1, 2)
        self.lblusername = QtWidgets.QLabel(self.groupBox_5)
        self.lblusername.setObjectName("lblusername")
        self.gridLayout_3.addWidget(self.lblusername, 1, 0, 1, 1)
        self.lneusername = QtWidgets.QLineEdit(self.groupBox_5)
        self.lneusername.setObjectName("lneusername")
        self.gridLayout_3.addWidget(self.lneusername, 1, 1, 1, 2)
        self.lnepassword = QtWidgets.QLineEdit(self.groupBox_5)
        self.lnepassword.setObjectName("lnepassword")
        self.gridLayout_3.addWidget(self.lnepassword, 2, 1, 1, 2)
        self.lblpassword = QtWidgets.QLabel(self.groupBox_5)
        self.lblpassword.setObjectName("lblpassword")
        self.gridLayout_3.addWidget(self.lblpassword, 2, 0, 1, 1)
        self.lblcheckfrequency = QtWidgets.QLabel(self.groupBox_5)
        self.lblcheckfrequency.setObjectName("lblcheckfrequency")
        self.gridLayout_3.addWidget(self.lblcheckfrequency, 6, 0, 1, 2)
        self.spncheckfrequency = QtWidgets.QSpinBox(self.groupBox_5)
        self.spncheckfrequency.setObjectName("spncheckfrequency")
        self.gridLayout_3.addWidget(self.spncheckfrequency, 6, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblnotifying = QtWidgets.QLabel(self.groupBox_5)
        self.lblnotifying.setObjectName("lblnotifying")
        self.gridLayout_4.addWidget(self.lblnotifying, 0, 0, 1, 1)
        self.chkmakebeep = QtWidgets.QCheckBox(self.groupBox_5)
        self.chkmakebeep.setMinimumSize(QtCore.QSize(371, 40))
        self.chkmakebeep.setObjectName("chkmakebeep")
        self.gridLayout_4.addWidget(self.chkmakebeep, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.chkplaysound = QtWidgets.QCheckBox(self.groupBox_5)
        self.chkplaysound.setMinimumSize(QtCore.QSize(371, 40))
        self.chkplaysound.setObjectName("chkplaysound")
        self.horizontalLayout_5.addWidget(self.chkplaysound)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(128, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.lnenotifyingsound = QtWidgets.QLineEdit(self.groupBox_5)
        self.lnenotifyingsound.setMinimumSize(QtCore.QSize(340, 30))
        self.lnenotifyingsound.setObjectName("lnenotifyingsound")
        self.horizontalLayout_6.addWidget(self.lnenotifyingsound)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_10.addWidget(self.frame_2)
        self.tabWidget.addTab(self.tabsettings, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(138, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btnquit = QtWidgets.QPushButton(MX5000)
        self.btnquit.setMinimumSize(QtCore.QSize(200, 45))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/application-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnquit.setIcon(icon3)
        self.btnquit.setIconSize(QtCore.QSize(48, 48))
        self.btnquit.setObjectName("btnquit")
        self.horizontalLayout.addWidget(self.btnquit)
        self.btnapply = QtWidgets.QPushButton(MX5000)
        self.btnapply.setMinimumSize(QtCore.QSize(200, 45))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/dialog-ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnapply.setIcon(icon4)
        self.btnapply.setIconSize(QtCore.QSize(48, 48))
        self.btnapply.setObjectName("btnapply")
        self.horizontalLayout.addWidget(self.btnapply)
        self.verticalLayout_6.addLayout(self.horizontalLayout)

        self.retranslateUi(MX5000)
        self.tabWidget.setCurrentIndex(0)
        self.btnquit.clicked.connect(MX5000.accept)
        QtCore.QMetaObject.connectSlotsByName(MX5000)

    def retranslateUi(self, MX5000):
        _translate = QtCore.QCoreApplication.translate
        MX5000.setWindowTitle(_translate("MX5000", "MX 5000"))
        self.groupBox.setTitle(_translate("MX5000", "Mails"))
        self.lblmails.setText(_translate("MX5000", "<html><head/><body><p>Check your mails immediatelly</p></body></html>"))
        self.btnchecknowmails.setText(_translate("MX5000", "Check now"))
        self.groupBox_2.setTitle(_translate("MX5000", "Log"))
        self.lbllog.setText(_translate("MX5000", "<html><head/><body><p> Log of your keyboard\'s activity</p></body></html>"))
        self.btnclearlog.setText(_translate("MX5000", "Clear log"))
        self.groupBox_3.setTitle(_translate("MX5000", "Keyboard"))
        self.lblkeyboard.setText(_translate("MX5000", "<html><head/><body><p>Sometimes the keyboard\'s LCD won\'t initialize</p><p>correctly, try this feature to correct it.</p></body></html>"))
        self.btnresetkeyboard.setText(_translate("MX5000", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabmain), _translate("MX5000", "Main"))
        self.groupBox_4.setTitle(_translate("MX5000", "General settings"))
        self.lblpathkeyboard.setText(_translate("MX5000", "<html><head/><body><p>Path to the keyboard</p></body></html>"))
        self.lblnamekeyboard.setText(_translate("MX5000", "<html><head/><body><p>Keyboard\'s name (max 11 characters)</p></body></html>"))
        self.groupBox_5.setTitle(_translate("MX5000", "Mail settings"))
        self.lblservertype.setText(_translate("MX5000", "<html><head/><body><p>Server type</p></body></html>"))
        self.rdbimap.setText(_translate("MX5000", "Imap"))
        self.rdbpop.setText(_translate("MX5000", "Pop"))
        self.lblserveradress.setText(_translate("MX5000", "<html><head/><body><p>Server adress</p></body></html>"))
        self.lblusername.setText(_translate("MX5000", "<html><head/><body><p>Username</p></body></html>"))
        self.lblpassword.setText(_translate("MX5000", "<html><head/><body><p>Password</p></body></html>"))
        self.lblcheckfrequency.setText(_translate("MX5000", "<html><head/><body><p>Check frequency (in minutes)</p></body></html>"))
        self.lblnotifying.setText(_translate("MX5000", "<html><head/><body><p>Notifying</p></body></html>"))
        self.chkmakebeep.setText(_translate("MX5000", "Make the keyboard beep"))
        self.chkplaysound.setText(_translate("MX5000", "Playsound (ogg or mp3) - not implemented yet"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabsettings), _translate("MX5000", "Settings"))
        self.btnquit.setText(_translate("MX5000", "Quit"))
        self.btnapply.setText(_translate("MX5000", "Apply"))
from images import mx5000ressources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MX5000 = QtWidgets.QDialog()
    ui = Ui_MX5000()
    ui.setupUi(MX5000)
    MX5000.show()
    sys.exit(app.exec_())
