# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageconverter.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 600)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblsourcefile = QtWidgets.QLabel(Dialog)
        self.lblsourcefile.setObjectName("lblsourcefile")
        self.horizontalLayout_3.addWidget(self.lblsourcefile)
        self.lnesourcefile = QtWidgets.QLineEdit(Dialog)
        self.lnesourcefile.setObjectName("lnesourcefile")
        self.horizontalLayout_3.addWidget(self.lnesourcefile)
        self.btninputfile = QtWidgets.QPushButton(Dialog)
        self.btninputfile.setMinimumSize(QtCore.QSize(175, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../.designer/backup/folder-blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btninputfile.setIcon(icon)
        self.btninputfile.setIconSize(QtCore.QSize(32, 32))
        self.btninputfile.setObjectName("btninputfile")
        self.horizontalLayout_3.addWidget(self.btninputfile)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbltargetformat = QtWidgets.QLabel(Dialog)
        self.lbltargetformat.setObjectName("lbltargetformat")
        self.horizontalLayout.addWidget(self.lbltargetformat)
        self.cmbtargetformat = QtWidgets.QComboBox(Dialog)
        self.cmbtargetformat.setMinimumSize(QtCore.QSize(260, 40))
        self.cmbtargetformat.setObjectName("cmbtargetformat")
        self.horizontalLayout.addWidget(self.cmbtargetformat)
        spacerItem = QtWidgets.QSpacerItem(175, 40, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gpbother = QtWidgets.QGroupBox(Dialog)
        self.gpbother.setObjectName("gpbother")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gpbother)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gpboptions = QtWidgets.QGroupBox(self.gpbother)
        self.gpboptions.setObjectName("gpboptions")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gpboptions)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chkenhance = QtWidgets.QCheckBox(self.gpboptions)
        self.chkenhance.setObjectName("chkenhance")
        self.horizontalLayout_4.addWidget(self.chkenhance)
        self.chkmonochrome = QtWidgets.QCheckBox(self.gpboptions)
        self.chkmonochrome.setObjectName("chkmonochrome")
        self.horizontalLayout_4.addWidget(self.chkmonochrome)
        self.verticalLayout.addWidget(self.gpboptions)
        self.outputtextedit = QtWidgets.QTextEdit(self.gpbother)
        self.outputtextedit.setObjectName("outputtextedit")
        self.verticalLayout.addWidget(self.outputtextedit)
        self.gridLayout_2.addWidget(self.gpbother, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(260, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnconvert = QtWidgets.QPushButton(Dialog)
        self.btnconvert.setMinimumSize(QtCore.QSize(175, 40))
        self.btnconvert.setIcon(icon)
        self.btnconvert.setIconSize(QtCore.QSize(32, 32))
        self.btnconvert.setObjectName("btnconvert")
        self.horizontalLayout_2.addWidget(self.btnconvert)
        self.btnquit = QtWidgets.QPushButton(Dialog)
        self.btnquit.setMinimumSize(QtCore.QSize(175, 40))
        self.btnquit.setIcon(icon)
        self.btnquit.setIconSize(QtCore.QSize(32, 32))
        self.btnquit.setObjectName("btnquit")
        self.horizontalLayout_2.addWidget(self.btnquit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        self.btnquit.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Image Converter"))
        self.lblsourcefile.setText(_translate("Dialog", "<html><head/><body><p>Source File:</p></body></html>"))
        self.btninputfile.setText(_translate("Dialog", "Input File"))
        self.lbltargetformat.setText(_translate("Dialog", "<html><head/><body><p>Target Format</p></body></html>"))
        self.gpboptions.setTitle(_translate("Dialog", "Options"))
        self.chkenhance.setText(_translate("Dialog", "Enhance"))
        self.chkmonochrome.setText(_translate("Dialog", "Monochrome"))
        self.btnconvert.setText(_translate("Dialog", "Convert"))
        self.btnquit.setText(_translate("Dialog", "Quit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

